apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-application
  template:
    metadata:
      labels:
        app: fastapi-application
    spec:
      containers:
      - name: fastapi-container
        image: us-east1-docker.pkg.dev/winter-clone-429310-f7/web/auth-service-image:latest
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: env-setup
        volumeMounts:
          - name: gcp-key
            mountPath: /var/secrets/google
            readOnly: true
        volumes:
          - name: gcp-key
            secret:
              secretName: gcp-service-account-key