apiVersion: batch/v1
kind: CronJob
metadata:
  name: rotate-kms-key
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gcloud-kms
            image: google/cloud-sdk:latest
            command:
              - /bin/sh
              - -c
              - |
                set -e  
                gcloud auth activate-service-account --key-file=/var/secrets/google/key.json
                gcloud config set project winter-clone-429310-f7
                
                KEY_VERSIONS=$(gcloud kms keys versions list --location global --keyring kms-key-ring --key kms-key --format="value(name)")
                for VERSION in $KEY_VERSIONS; do
                  STATUS=$(gcloud kms keys versions describe $VERSION --location global --keyring kms-key-ring --key kms-key --format="value(state)")
                  if [ "$STATUS" != "DESTROY_SCHEDULED" ]; then
                    gcloud kms keys versions destroy $VERSION --location global --keyring kms-key-ring --key kms-key --quiet || true
                  fi
                done
                
                gcloud kms keys versions create \
                --location global \
                --keyring kms-key-ring \
                --key kms-key
            volumeMounts:
              - name: gcp-key
                mountPath: /var/secrets/google
                readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: gcp-key
            secret:
              secretName: gcp-service-account-key
