apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-application
       #app: myapp
  template:
    metadata:
      labels:
        app: django-application
         #app: myapp
    spec:
      containers:
      - name: django-container
        image: us-east1-docker.pkg.dev/phrasal-lantern-435910-c4/web/web-server-image:latest
        #image: hayko2508/django-image:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: env-config
