# Generated by Django 5.0.6 on 2024-06-11 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParsedObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("obj_type", models.CharField()),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Parser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(unique=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImageParsedObject",
            fields=[
                (
                    "parsedobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="parsers.parsedobject",
                    ),
                ),
                ("image_url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
            bases=("parsers.parsedobject",),
        ),
        migrations.CreateModel(
            name="VideoParsedObject",
            fields=[
                (
                    "parsedobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="parsers.parsedobject",
                    ),
                ),
                ("video_url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
            bases=("parsers.parsedobject",),
        ),
        migrations.CreateModel(
            name="ImageParser",
            fields=[
                (
                    "parser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="parsers.parser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("parsers.parser",),
        ),
        migrations.CreateModel(
            name="VideoParser",
            fields=[
                (
                    "parser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="parsers.parser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("parsers.parser",),
        ),
        migrations.AddField(
            model_name="parsedobject",
            name="parser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parsers.parser"
            ),
        ),
    ]
