# Generated by Django 5.0.6 on 2024-06-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parsers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageParsedObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
