# Generated by Django 5.0.6 on 2024-06-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parsers", "0002_remove_parsedobject_obj_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parser",
            name="url",
            field=models.URLField(),
        ),
    ]
