# Generated by Django 5.0.6 on 2024-06-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parsers", "0007_alter_url_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageparsedobject",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="videoparsedobject",
            name="polymorphic_ctype",
        ),
    ]
