name: Lint

on:
  pull_request:
    paths:
      - '.github/workflows/black-format.yml'
      - 'web-server/**'
      - 'services/FAuth/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable